--ex 4 ,db movies

--4.1.1
SELECT mv1.TITLE, mx1.NAME
FROM MOVIE as mv1 JOIN  MOVIEEXEC as mx1 ON mv1.PRODUCERC# = mx1.CERT#
WHERE mv1.PRODUCERC# = (SELECT mv2.PRODUCERC#
						FROM MOVIE as mv2 
						WHERE mv2.TITLE = 'Star Wars');

--4.1.2
SELECT mx1.NAME
FROM MOVIEEXEC as mx1 JOIN MOVIE as mv1 ON mx1.CERT# = mv1.PRODUCERC#
WHERE mv1.TITLE IN (SELECT st.MOVIETITLE
					FROM  STARSIN as st
					WHERE st.STARNAME = 'Harrison Ford');

--4.1.3
SELECT DISTINCT mv1.STUDIONAME, star.STARNAME
FROM MOVIE as mv1 JOIN STARSIN as star ON mv1.TITLE = star.MOVIETITLE
ORDER BY mv1.STUDIONAME;

--4.1.4
SELECT st1.STARNAME, mx1.NETWORTH, mv1.TITLE
FROM STARSIN as st1 JOIN MOVIE as mv1 ON st1.MOVIETITLE = mv1.TITLE JOIN MOVIEEXEC as mx1 ON mv1.PRODUCERC# = mx1.CERT#
WHERE mx1.NETWORTH >=ALL(SELECT mx2.NETWORTH FROM MOVIEEXEC as mx2);

--4.1.5
SELECT mst.NAME, st.MOVIETITLE
FROM STARSIN as st FULL JOIN MOVIESTAR mst ON st.STARNAME = mst.NAME
WHERE st.STARNAME IS NULL AND mst.NAME IS NOT NULL
